name: Call a reusable workflow

on: push

jobs:
  call-workflow-passing-data:
    steps:
      - name: Call workflow
        uses: thomasheyenbrock/subscriptions-example/.github/workflows/a.yml@main
        with:
          username: thomasheyenbrock
