name: Call a reusable workflow

on: push

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  before-call:
    name: Echo env
    runs-on: ubuntu-latest
    steps:
      - name: Echo env
        run: echo "${{ env.TEST_ENV }}"
  call-workflow-passing-data:
    needs:
      - before-call
    uses: thomasheyenbrock/subscriptions-example/.github/workflows/a.yml@main
    with:
      username: thomasheyenbrock
  after-call:
    name: Echo env
    runs-on: ubuntu-latest
    needs:
      - call-workflow-passing-data
    steps:
      - name: Echo env
        run: echo "${{ env.TEST_ENV }}"
